# Generated by Django 4.2.16 on 2024-10-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('BMW', 'BMW'), ('Mercedes', 'Mercedes'), ('Volvo', 'Volvo'), ('Porsche', 'Porsche'), ('Jeep', 'Jeep'), ('Audi', 'Audi'), ('Ferrari', 'Ferrari')], max_length=50)),
                ('number_of_seats', models.PositiveIntegerField(choices=[(2, '2 seats'), (4, '4 seats'), (5, '5 seats'), (7, '7 seats')])),
                ('number_of_doors', models.PositiveIntegerField(choices=[(2, '2 doors'), (4, '4 doors')])),
                ('sunroof', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('automatic', models.BooleanField(choices=[(True, 'Automatic'), (False, 'Manual')])),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('car_type', models.CharField(choices=[('touring', 'Touring Cars'), ('hiking', 'Hiking Cars'), ('camping', 'Camping Cars')], max_length=20)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('white', 'White'), ('silver', 'Silver'), ('yellow', 'Yellow'), ('gray', 'Gray')], max_length=20)),
            ],
        ),
    ]
