# Generated by Django 4.2.16 on 2024-10-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('additional_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pickup_address', models.TextField()),
                ('return_address', models.TextField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('master', 'MasterCard'), ('visa', 'Visa')], max_length=10)),
                ('card_name', models.CharField(max_length=50, null=True)),
                ('card_number', models.CharField(max_length=16, null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('cvv', models.CharField(max_length=4, null=True)),
            ],
        ),
    ]
